changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
    authors:
      - dependabot
      - github-actions
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - feature
        - enhancement
        - semver-minor
    - title: Bug Fixes
      labels:
        - bug
        - fix
        - semver-patch
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: CI and Packaging
      labels:
        - ci
        - packaging
        - release
    - title: Chores
      labels:
        - chore
        - dependencies
    - title: Other Changes
      labels:
        - "*"
